global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'proposta'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.1.75:8080']
#    oauth2:
#      client_id: 'prometheus'
#      client_secret_file: secret.txt
#      scopes:
#        - 'prometheus'
#      token_url: 'http://keycloak:8080/auth/realms/proposta/protocol/openid-connect/token'
